export const BUTTON_TYPE_WHITE = "BUTTON_TYPE_WHITE";
export const BUTTON_TYPE_DARK = "BUTTON_TYPE_DARK";
export const BUTTON_TYPE_GREEN = "BUTTON_TYPE_GREEN";
export const BUTTON_TYPE_RED = "BUTTON_TYPE_RED";
